//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FishClubAlginet.Application.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FishClubAlginet.Application.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation password must match the password..
        /// </summary>
        internal static string Auth_ConfirmPassword_MustMatch {
            get {
                return ResourceManager.GetString("Auth_ConfirmPassword_MustMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email format is not valid..
        /// </summary>
        internal static string Auth_Email_InvalidFormat {
            get {
                return ResourceManager.GetString("Auth_Email_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string Auth_Email_Required {
            get {
                return ResourceManager.GetString("Auth_Email_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided credentials are invalid..
        /// </summary>
        internal static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must be at least 6 characters long..
        /// </summary>
        internal static string Auth_Password_MinLength {
            get {
                return ResourceManager.GetString("Auth_Password_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        internal static string Auth_Password_Required {
            get {
                return ResourceManager.GetString("Auth_Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        internal static string Auth_PasswordMismatch {
            get {
                return ResourceManager.GetString("Auth_PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to generate the authentication token..
        /// </summary>
        internal static string Auth_TokenGenerationFailed {
            get {
                return ResourceManager.GetString("Auth_TokenGenerationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A record with these unique values already exists..
        /// </summary>
        internal static string Database_DuplicateEntry {
            get {
                return ResourceManager.GetString("Database_DuplicateEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save the record. Please try again..
        /// </summary>
        internal static string Database_SaveFailure {
            get {
                return ResourceManager.GetString("Database_SaveFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth must be in the past..
        /// </summary>
        internal static string Fisherman_BirthDate_InPast {
            get {
                return ResourceManager.GetString("Fisherman_BirthDate_InPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number is invalid: the check letter does not match..
        /// </summary>
        internal static string Fisherman_DocumentNumber_InvalidControlLetter {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_InvalidControlLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number can only contain letters, numbers, hyphens, and spaces..
        /// </summary>
        internal static string Fisherman_DocumentNumber_InvalidFormat {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_InvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number cannot exceed {0} characters..
        /// </summary>
        internal static string Fisherman_DocumentNumber_MaxLength {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number must be at least {0} characters long..
        /// </summary>
        internal static string Fisherman_DocumentNumber_MinLength {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number cannot be empty or whitespace only..
        /// </summary>
        internal static string Fisherman_DocumentNumber_NotWhitespace {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_NotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document number is required..
        /// </summary>
        internal static string Fisherman_DocumentNumber_Required {
            get {
                return ResourceManager.GetString("Fisherman_DocumentNumber_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document type is not valid..
        /// </summary>
        internal static string Fisherman_DocumentType_Invalid {
            get {
                return ResourceManager.GetString("Fisherman_DocumentType_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fisherman with this federation license already exists..
        /// </summary>
        internal static string Fisherman_DuplicateLicense {
            get {
                return ResourceManager.GetString("Fisherman_DuplicateLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Federation license cannot exceed {0} characters..
        /// </summary>
        internal static string Fisherman_FederationLicense_MaxLength {
            get {
                return ResourceManager.GetString("Fisherman_FederationLicense_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot exceed {0} characters..
        /// </summary>
        internal static string Fisherman_FirstName_MaxLength {
            get {
                return ResourceManager.GetString("Fisherman_FirstName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name cannot be empty or whitespace only..
        /// </summary>
        internal static string Fisherman_FirstName_NotWhitespace {
            get {
                return ResourceManager.GetString("Fisherman_FirstName_NotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name is required..
        /// </summary>
        internal static string Fisherman_FirstName_Required {
            get {
                return ResourceManager.GetString("Fisherman_FirstName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The document number is not valid for the selected document type..
        /// </summary>
        internal static string Fisherman_InvalidDocument {
            get {
                return ResourceManager.GetString("Fisherman_InvalidDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot exceed {0} characters..
        /// </summary>
        internal static string Fisherman_LastName_MaxLength {
            get {
                return ResourceManager.GetString("Fisherman_LastName_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name cannot be empty or whitespace only..
        /// </summary>
        internal static string Fisherman_LastName_NotWhitespace {
            get {
                return ResourceManager.GetString("Fisherman_LastName_NotWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name is required..
        /// </summary>
        internal static string Fisherman_LastName_Required {
            get {
                return ResourceManager.GetString("Fisherman_LastName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fisherman must be at least {0} years old..
        /// </summary>
        internal static string Fisherman_MinimumAge {
            get {
                return ResourceManager.GetString("Fisherman_MinimumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The requested fisherman does not exist..
        /// </summary>
        internal static string Fisherman_NotFound {
            get {
                return ResourceManager.GetString("Fisherman_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to block the user..
        /// </summary>
        internal static string User_BlockFailed {
            get {
                return ResourceManager.GetString("User_BlockFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve users. Please try again..
        /// </summary>
        internal static string User_GetAllFailed {
            get {
                return ResourceManager.GetString("User_GetAllFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified role is not valid..
        /// </summary>
        internal static string User_InvalidRole {
            get {
                return ResourceManager.GetString("User_InvalidRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string User_NotFound {
            get {
                return ResourceManager.GetString("User_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to assign the role to the user..
        /// </summary>
        internal static string User_RoleAssignFailed {
            get {
                return ResourceManager.GetString("User_RoleAssignFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to unblock the user..
        /// </summary>
        internal static string User_UnblockFailed {
            get {
                return ResourceManager.GetString("User_UnblockFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Failed to remove the role from the user..
        /// </summary>
        internal static string User_RoleRemoveFailed {
            get {
                return ResourceManager.GetString("User_RoleRemoveFailed", resourceCulture);
            }
        }
    }
}
